import type { Product, Blog } from './types';

export const products: Product[] = [
  {
    id: '1',
    slug: 'organic-royal-gala-apples',
    name: 'Organic Royal Gala Apples',
    description: 'Crisp, sweet, and perfect for snacking.',
    longDescription: 'Our Organic Royal Gala Apples are sourced from local orchards in the Hawke\'s Bay region. Known for their reddish-pink skin and sweet, crisp flesh, they are perfect for eating fresh, adding to salads, or baking into pies. Grown without synthetic pesticides, they are a healthy and delicious choice.',
    price: 6.99,
    images: ['https://picsum.photos/seed/apple/800/800', 'https://picsum.photos/seed/apple2/800/800', 'https://picsum.photos/seed/apple3/800/800'],
    category: 'Fruits',
    isOrganic: true,
    isSeasonal: true,
    stock: 150,
    rating: 4.8,
    reviews: 120,
  },
  {
    id: '2',
    slug: 'hass-avocados',
    name: 'Hass Avocados',
    description: 'Creamy and rich, ideal for toast or salads.',
    longDescription: 'These creamy Hass Avocados are grown in the Bay of Plenty. They have a rich, nutty flavor and a buttery texture that makes them perfect for spreading on toast, adding to smoothies, or making guacamole. Packed with healthy fats and nutrients.',
    price: 2.50,
    images: ['https://picsum.photos/seed/avocado/800/800', 'https://picsum.photos/seed/avocado2/800/800'],
    category: 'Fruits',
    isOrganic: false,
    isSeasonal: true,
    stock: 200,
    rating: 4.9,
    reviews: 250,
  },
  {
    id: '3',
    slug: 'agria-potatoes',
    name: 'Agria Potatoes',
    description: 'Fluffy texture, excellent for roasting and mashing.',
    longDescription: 'Agria Potatoes from Canterbury are a versatile favorite. Their yellow flesh and fluffy texture make them ideal for roasting, mashing, and making chips. A staple in any Kiwi kitchen, they offer a delicious, earthy flavor.',
    price: 4.50,
    images: ['https://picsum.photos/seed/potato/800/800', 'https://picsum.photos/seed/potato2/800/800'],
    category: 'Vegetables',
    isOrganic: false,
    isSeasonal: false,
    stock: 300,
    rating: 4.7,
    reviews: 95,
  },
  {
    id: '4',
    slug: 'organic-carrots',
    name: 'Organic Carrots',
    description: 'Sweet and crunchy, packed with vitamins.',
    longDescription: 'Our organic carrots are grown in the fertile soils of Pukekohe. They are known for their sweet flavor and satisfying crunch. Perfect for snacking, juicing, or adding to stews and roasts. Certified organic and full of beta-carotene.',
    price: 3.99,
    images: ['https://picsum.photos/seed/carrot/800/800', 'https://picsum.photos/seed/carrot2/800/800'],
    category: 'Vegetables',
    isOrganic: true,
    isSeasonal: false,
    stock: 180,
    rating: 4.6,
    reviews: 88,
  },
  {
    id: '5',
    slug: 'gold-kiwifruit',
    name: 'Gold Kiwifruit',
    description: 'Sweet, tropical, and bursting with Vitamin C.',
    longDescription: 'A true New Zealand icon, our Gold Kiwifruit is sweeter and less acidic than its green counterpart. With a smooth, hairless skin and a tropical flavor, it\'s a delicious way to boost your Vitamin C intake. Sourced from Te Puke, the kiwifruit capital of the world.',
    price: 7.50,
    images: ['https://picsum.photos/seed/kiwi/800/800', 'https://picsum.photos/seed/kiwi2/800/800'],
    category: 'Fruits',
    isOrganic: false,
    isSeasonal: true,
    stock: 120,
    rating: 5.0,
    reviews: 310,
  },
  {
    id: '6',
    slug: 'fresh-broccoli',
    name: 'Fresh Broccoli',
    description: 'Nutrient-dense and great for steaming or stir-frying.',
    longDescription: 'This fresh broccoli is harvested at its peak to ensure maximum flavor and nutritional value. With its firm stalks and vibrant green florets, it\'s a versatile vegetable that can be steamed, roasted, or added to stir-fries. A fantastic source of vitamins K and C.',
    price: 3.20,
    images: ['https://picsum.photos/seed/broccoli/800/800'],
    category: 'Vegetables',
    isOrganic: false,
    isSeasonal: false,
    stock: 90,
    rating: 4.5,
    reviews: 75,
  },
  {
    id: '7',
    slug: 'seasonal-organic-box',
    name: 'Seasonal Organic Box',
    description: 'A curated mix of the best seasonal organic produce.',
    longDescription: 'Our Seasonal Organic Box is a fantastic way to enjoy the best of what the season has to offer. Each week, we curate a selection of fresh, certified organic fruits and vegetables from our partner farms. The contents vary based on availability, ensuring you always get the freshest, most flavorful produce.',
    price: 55.00,
    images: ['https://picsum.photos/seed/box/800/800', 'https://picsum.photos/seed/box2/800/800'],
    category: 'Organic Boxes',
    isOrganic: true,
    isSeasonal: true,
    stock: 50,
    rating: 4.9,
    reviews: 150,
  },
  {
    id: '8',
    slug: 'mixed-leaf-salad',
    name: 'Mixed Leaf Salad',
    description: 'A fresh and zesty mix of organic salad greens.',
    longDescription: 'Ready for your favorite dressing, our Mixed Leaf Salad is a convenient and healthy choice. It features a blend of organic lettuce varieties, spinach, and rocket, offering a range of textures and flavors. Triple-washed and ready to eat.',
    price: 5.50,
    images: ['https://picsum.photos/seed/salad/800/800'],
    category: 'Vegetables',
    isOrganic: true,
    isSeasonal: false,
    stock: 110,
    rating: 4.7,
    reviews: 65,
  },
];

export const blogPosts: Blog[] = [
  {
    id: '1',
    slug: 'benefits-of-eating-seasonally',
    title: 'The Benefits of Eating Seasonally in New Zealand',
    excerpt: 'Discover why choosing seasonal produce is not only better for your health but also for the environment and local economy.',
    content: 'Eating seasonally means enjoying produce at its peak flavor and nutritional value. In New Zealand, this means juicy strawberries in summer and hearty root vegetables in winter. By aligning our diets with the seasons, we support local farmers, reduce food miles, and connect more deeply with the natural cycles of our beautiful country.',
    imageUrl: 'https://picsum.photos/seed/blog1/1200/800',
    author: 'Jane Doe',
    date: 'October 26, 2023',
  },
  {
    id: '2',
    slug: 'our-favourite-kiwi-summer-salad',
    title: 'Our Favourite Kiwi Summer Salad Recipe',
    excerpt: 'A refreshing and simple salad recipe perfect for a summer BBQ, featuring the best of New Zealand\'s summer produce.',
    content: 'This recipe combines sweet corn, ripe avocados, cherry tomatoes, and a zesty lime dressing. It\'s the perfect accompaniment to grilled meats or fish. The key is using the freshest ingredients, which you can find right here at Aotearoa Organics. It\'s a taste of a Kiwi summer in every bite!',
    imageUrl: 'https://picsum.photos/seed/blog2/1200/800',
    author: 'John Smith',
    date: 'November 15, 2023',
  },
  {
    id: '3',
    slug: 'guide-to-organic-farming',
    title: 'A Beginner\'s Guide to Organic Farming',
    excerpt: 'Ever wondered what "organic" really means? We break down the principles of organic farming and why it matters.',
    content: 'Organic farming is a holistic approach to agriculture that focuses on soil health, biodiversity, and ecological balance. It avoids synthetic pesticides and fertilizers, promoting a sustainable system that works in harmony with nature. When you choose organic, you\'re supporting a healthier planet and a more resilient food system.',
    imageUrl: 'https://picsum.photos/seed/blog3/1200/800',
    author: 'Emily White',
    date: 'December 02, 2023',
  },
];
